services:
  odoo:
    image: odoo:17
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072" # live chat
    environment:
      SERVICE_FQDN_ODOO_8069:
      HOST: db
      USER: '${SERVICE_USER_POSTGRES}'
      PASSWORD: '${SERVICE_PASSWORD_POSTGRES}'
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./addons:/mnt/extra-addons
      - odoo-data:/var/lib/odoo
      - type: bind
        source: ./l10n_ve
        target: /mnt/l10n_ve_addons
      - type: bind
        source: ./config/odoo.conf
        target: /etc/odoo/odoo.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8069"]
      interval: 2s
      timeout: 10s
      retries: 30

  db:
    image: postgres:17-alpine
    environment:
      PGPASSWORD: '${SERVICE_PASSWORD_POSTGRES}'
      POSTGRES_DB: postgres
      POSTGRES_USER: '${SERVICE_USER_POSTGRES}'
      POSTGRES_PASSWORD: '${SERVICE_PASSWORD_POSTGRES}'
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d postgres"]
      interval: 5s
      timeout: 20s
      retries: 10

volumes:
  db-data:
  odoo-data: